# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Support lane for building on a fresh simulator w/o a previous app install
  lane :prepare_simulator do |options|
    simulator_name = options[:device_name]

    UI.message("Pre-building app")

    project_path = File.expand_path("../iOS Platform Assessment.xcodeproj", __dir__)

    sh "xcodebuild -project '#{project_path}' \
      -scheme 'iOS Platform Assessment' \
      -destination 'platform=iOS Simulator,name=#{simulator_name}' \
      build"
  end

  # Support lane for running tests
  desc "Run tests given a test target's scheme name"
  lane :execute_tests do |options|
    prepare_simulator(device_name:"iPhone 16 Pro") # Comment out this step if you already have an app build on the simulator
    scan(
      scheme: options[:scheme],
      project: "./iOS Platform Assessment.xcodeproj",
      devices: ["iPhone 16 Pro"],
      output_types: "junit,html",
      output_directory: "fastlane/test_output/#{options[:scheme]}"
    )
  end

  # Unit test lane
  desc "A custom fastlane lane to run the unit tests"
  lane :unit_test do
    execute_tests(scheme: "iOS Platform AssessmentTests")
  end

  # UI test lane
  desc "A custom fastlane lane to run the UI tests"
  lane :ui_test do
    execute_tests(scheme: "iOS Platform AssessmentUITests")
  end


  # Upload to App Store lane
  desc "Using using App Store Connect API key authentication"
  lane :submit_to_app_store do
    app_store_connect_api_key(
      key_id: "ABC123", # Fake key
      issuer_id: "11223344-5566-7788-9900-aabbccddeeff",  # Fake issuer ID
      key_filepath: "./fakeKey.p8", # Fake path to API key file, throws bad elliptic curve error since it's not a real private key
      in_house: false
    )

    # Increment build number (optional, for CI)
    increment_build_number(
    xcodeproj: "./iOS Platform Assessment.xcodeproj"
    )

    # Build and sign the app
    build_app(
      scheme: "iOS Platform Assessment",
      export_method: "app-store",
      output_directory: "fastlane/build",
      output_name: "iOS Platform Assessment.ipa"
    )

    # Upload the IPA
    upload_to_app_store(
      skip_screenshot_upload: true,
      skip_metadata: true,
      ipa: "fastlane/build/iOS Platform Assessment.ipa"
    )
  end

end
