# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Support lane for running tests
  desc "Run tests given a test target's scheme name"
  lane :execute_tests do |options|
    scan(
      scheme: options[:scheme],
      device: "iPhone 16 Pro",
      clean: true,
      build_for_testing: true,
      output_directory: "fastlane/test_output/#{options[:scheme]}",
      output_types: "junit, html",
      fail_build: true
     )
  end

  # Unit test lane
  desc "A custom fastlane lane to run the unit tests"
  lane :unit_test do
    execute_tests(scheme: "iOS Platform AssessmentTests")
  end

  # UI test lane
  desc "A custom fastlane lane to run the UI tests"
  lane :ui_test do
    execute_tests(scheme: "iOS Platform AssessmentUITests")
  end
end
