# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # Support lane for building on a fresh simulator w/o a previous app install
  lane :prepare_simulator do |options|
    simulator_name = options[:device_name]

    UI.message("Booting and preparing simulator: #{simulator_name}")

    project_path = File.expand_path("../iOS Platform Assessment.xcodeproj", __dir__)

    sh "xcodebuild -project '#{project_path}' \
      -scheme 'iOS Platform Assessment' \
      -destination 'platform=iOS Simulator,name=#{simulator_name}' \
      build"
    end

  # Support lane for running tests
  desc "Run tests given a test target's scheme name"
  lane :execute_tests do |options|
    prepare_simulator(device_name:"iPhone 16 Pro") # Comment out this step if you already have an app build on the simulator
    scan(
      scheme: options[:scheme],
      project: "./iOS Platform Assessment.xcodeproj",
      devices: ["iPhone 16 Pro"],
      output_types: "junit,html",
      output_directory: "fastlane/test_output/#{options[:scheme]}"
    )
  end

  # Unit test lane
  desc "A custom fastlane lane to run the unit tests"
  lane :unit_test do
    execute_tests(scheme: "iOS Platform AssessmentTests")
  end

  # UI test lane
  desc "A custom fastlane lane to run the UI tests"
  lane :ui_test do
    execute_tests(scheme: "iOS Platform AssessmentUITests")
  end
end
